learning_template/basic_app/urls.py
from django.conf.urls import url
from . import views

#TEMPLATE TAGGING
app_name =  'basic_app'
urlpatterns = [

url(r'^relative/$',views.relative,name = 'relative'),
url(r'^other/$',views.other,name = 'other'),
]

learning_template/learning_template/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

learning_template/basic_app/models.py
from django.db import models

# Create your models here.

learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

learning_template/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", rel="stylesheet", integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>


          </ul>
        </div>
    </nav>
    <div class="container">
      {%  block body_block %}
      <!--Anything outside of this will be inherited if you extend-->
      {% endblock %}
    </div>
  </body>
</html>

learning_template/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <center>
    <h1 style="color:red">WELCOME TO INDEX</h1>
    <h2 style="color:lightpink">This is an Example of  template inheritance</h2><br>

      <a href="{% url 'basic_app:other'%}">The Other page</a><br>
        <a href="{% url 'basic_app:relative'%}">The Relative page</a><br>
        <a href="{% url 'admin:index' %}">Link to Admin</a><br>
        <h3>{{text|cut:'World'}}</h3>
        <h4>{{number|add:"99"}}</h4>
  </center>
{% endblock %}

learning_template/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <center>
    <h1 style="color:green">WELCOME TO OTHER</h1><br>
    <h2 style="color:lightgreen">This is an Example of  template inheritance</h2><br>
    <a href="{% url 'basic_app:relative'%}">The Relative page</a><br>
    <a href="{% url 'admin:index' %}">Link to Admin</a><br>
    <a href="{% url 'index' %}">Index page</a>
{% endblock %}

learning_template/templates/basic_app/relative_url_template.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <center>
    <h1 style="color:cyan">WELCOME TO RELATIVE URL TEMPLATE</h1>
    <h2 style="color:lightblue">This is an Example of  template inheritance</h2><br>
    <a href="{% url 'basic_app:other' %}">The Other page</a><br>
      <a href="{% url 'admin:index' %}">Link to Admin</a><br>
      <a href="{% url 'index' %}">Index page</a><br>
  </center>
{% endblock %}